#
# Jenkins pipeline for CNaaS
#

disabled: false

git:
  branch: master
  extensions:
    shallow_clone: true

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install --upgrade setuptools pip wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements.txt"
  - "nosetests --with-xunit

# slack:
#   room: "cnaas"

extra_jobs:
  - name: cnaas-httpd
    builders:
      - docker
    docker_name: cnaas/httpd
    docker_context_dir: docker/httpd
    triggers:
      github_push: true

  - name: cnaas-dhcpd
    builders:
      - docker
    docker_name: cnaas/dhcpd
    docker_context_dir: docker/dhcpd
    triggers:
      github_push: true

  - name: cnaas-api
    builders:
      - docker
    docker_name: cnaas/api
    docker_context_dir: docker/api
    triggers:
      github_push: true
