#
# Jenkins pipeline for CNaaS
#

disabled: false

downstream:
  - cnaas-httpd
  - cnaas-dhcpd
  - cnaas-api
  - cnaas-postgres
  
git:
  branch: master
  extensions:
    shallow_clone: true

script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install --upgrade setuptools pip wheel mypy"
  - "pip install --index-url https://pypi.sunet.se -r requirements.txt"
  - "nosetests --with-xunit"

# slack:
#   room: "cnaas"

extra_jobs:
  - name: cnaas-httpd
    builders:
      - docker
    docker_name: cnaas_httpd
    docker_context_dir: docker/httpd

  - name: cnaas-dhcpd
    builders:
      - docker
    docker_name: cnaas_dhcpd
    docker_context_dir: docker/dhcpd

  - name: cnaas-api
    builders:
      - docker
    docker_name: cnaas_api
    docker_context_dir: docker/api

  - name: cnaas-postgres
    builders:
      - docker
    docker_name: cnaas_postgres
    docker_context_dir: docker/postgres
