version: '3.7'
services:
  cnaas_api:
    build: ./api/
    ports:
      - 5000:5000
    networks:
      - cnaas
    environment:
      - GITREPO_TEMPLATES
      - GITREPO_SETTINGS
    depends_on:
      - "cnaas_postgres"
  cnaas_postgres:
    build: ./postgres/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cnaas
      - POSTGRES_PASSWD=cnaas
      - POSTGRES_DB=cnaas
    networks:
      - cnaas
  cnaas_httpd:
    build: ./httpd/
    ports:
      - 80:80
    networks:
      - cnaas
    environment:
      - GITREPO_TEMPLATES
  cnaas_dhcpd:
    build: ./dhcpd/
    ports:
      - 67:67/udp
    networks:
      - cnaas
    environment:
      - GITREPO_ETC
      - DB_PASSWORD=cnaas
      - DB_HOSTNAME=docker_cnaas_postgres_1
    depends_on:
      - "cnaas_httpd"
      - "cnaas_api"
networks:
  cnaas:
    driver: bridge
    name: cnaas
    ipam:
      config:
      - subnet: 172.18.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br-cnaas
