apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cnaas-postgres
  name: cnaas-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cnaas-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: cnaas-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cnaas
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnaas-credentials
                  key: cnaas-db-password
            - name: POSTGRES_USER
              value: cnaas
          image: {{ .Values.postgres.image }}
          name: cnaas-postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cnaas-postgres-data
              subPath: postgres
            # - name: secrets-store01-inline
            #   mountPath: "/mnt/secrets-store"
            #   readOnly: true
      restartPolicy: Always
      volumes:
        - name: cnaas-postgres-data
          persistentVolumeClaim:
            claimName: cnaas-postgres-data
        # - name: secrets-store01-inline
        #   csi:
        #     driver: secrets-store.csi.k8s.io
        #     readOnly: true
        #     volumeAttributes:
        #       secretProviderClass: "azure-kvname-user-msi"
status: {}
