apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure   
  secretObjects: 
  - secretName: cnaas-credentials 
    type: Opaque                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    data:
    - objectName: cnaas-db-password 
      key: cnaas-db-password  
    - objectName: git-token
      key: git-token
    - objectName: jwt-auth-token 
      key: jwt-auth-token
    - objectName: cnaas-dhcpd-password
      key: cnaas-dhcpd-password 
    - objectName: cnaas-discovered-password 
      key: cnaas-discovered-password
    - objectName: cnaas-init-password 
      key: cnaas-init-password  
    - objectName: cnaas-managed-password
      key: cnaas-managed-password
    - objectName: template-admin-hash 
      key: template-admin-hash
    - objectName: template-radius-hash 
      key: template-radius-hash
    - objectName: cnaas-db-hostname
      key: cnaas-db-hostname
    - objectName: cnaas-db-name
      key: cnaas-db-name
    - objectName: template-secret-snmp-community
      key: template-secret-snmp-community
    - objectName: api-key-netbox
      key: api-key-netbox
  - secretName: cnaas-ca 
    type: Opaque
    data:    
    - objectName: ca-key
      key: rootCA.key
    - objectName: ca-crt
      key: rootCA.crt
  - secretName: nginx-certs
    type: Opaque
    data:    
    - objectName: snakeoil-key
      key: cnaas_snakeoil.key
    - objectName: snakeoil-crt
      key: cnaas_snakeoil.crt
  - secretName: cnaas-pub
    type: Opaque
    data:         
    - objectName: public-pem
      key: public.pem 
  - secretName: auth-certs
    type: Opaque
    data:
    - objectName: auth-private-pem
      key: private.pem   
    - objectName: auth-public-pem
      key: public.pem                # data field to populate                  # name of the mounted content to sync. this could be the object name or the object alias                  # name of the Kubernetes Secret object                 # The tenant ID of the key vault
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.csidriver.managedidentityclientid }} #"870c5eb3-bd9c-4c77-85b9-e9a436414e60"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: {{ .Values.csidriver.keyvaultname }}    # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: cnaas-db-password
          objectType: secret
        - |
          objectName: cnaas-db-hostname
          objectType: secret
        - |
          objectName: cnaas-db-name
          objectType: secret
        - |
          objectName: git-token
          objectType: secret
        - |
          objectName: jwt-auth-token
          objectType: secret
        - |
          objectName: cnaas-dhcpd-password
          objectType: secret
        - |
          objectName: cnaas-discovered-password
          objectType: secret
        - |
          objectName: cnaas-managed-password
          objectType: secret
        - |
          objectName: cnaas-init-password
          objectType: secret
        - |
          objectName: template-admin-hash
          objectType: secret
        - |
          objectName: template-radius-hash
          objectType: secret
        - |
          objectName: ca-key
          objectType: secret
        - |
          objectName: ca-crt
          objectType: secret
        - |
          objectName: public-pem
          objectType: secret
        - |
          objectName: snakeoil-crt
          objectType: secret
        - |
          objectName: snakeoil-key
          objectType: secret
        - |
          objectName: auth-private-pem
          objectType: secret
        - |
          objectName: auth-public-pem
          objectType: secret
        - |
          objectName: template-secret-snmp-community
          objectType: secret
        - |
          objectName: api-key-netbox
          objectType: secret
    tenantId: "0cd9bc36-9c09-4562-8d35-e911c1f68a7a"